version: '3.8'

services:
  db:
    container_name: base_db
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=base_core
    networks:
      - student
#  web:
#     container_name: base_web
#     image: hxuan190/server
#     ports:
#       - "8001:8080"
##     environment:
##       - ASPNETCORE_ENVIRONMENT=Production
##       - ConnectionStrings__Default=Server=base_db;Port=3307;Database=base_core;User=root;Password=123456
#     depends_on:
#       - db
#     networks:
#       - student

volumes:
  mysql_data:

networks:
  student: